#!/bin/bash

# this script will download fabric, enable universe sources, update source list, 
# install packages that are needed for fabric, install fabric, download the
# project fabfile.

wget http://git.fabfile.org/cgit.cgi/fabric/snapshot/fabric-1.4.0.tar.gz
wget http://myy.haaga-helia.fi/~a0900094/awasebg.jpg
tar -xf fabric-1.4.0.tar.gz
sudo software-properties-gtk -e universe
sudo apt-get update
sudo apt-get install python python-pycryptopp python-setuptools python-paramiko
cd fabric-1.4.0/
sudo python setup.py install
cd
wget https://raw.github.com/AwaseConfigurations/main/master/fabric/fabfile.py
fab -l
